FROM nginx:alpine

LABEL org.opencontainers.image.source=https://github.com/akulatraxas/local-webapp-demo.git
LABEL org.opencontainers.image.documentation=https://github.com/akulatraxas/local-webapp-demo
LABEL org.opencontainers.image.vendor=Akulatraxas

COPY index.html /usr/share/nginx/html/index.html
