name: Build and Update GitOps

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # local-webapp-demo
  IMAGE_BACKEND: ghcr.io/akulatraxas/local-webapp-demo-backend
  IMAGE_FRONTEND: ghcr.io/akulatraxas/local-webapp-demo-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v4

      # 1. Use the official Login Action
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Build and Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:${{ github.sha }}, ${{ env.IMAGE_BACKEND }:latest

      # 3. Build and Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}, ${{ env.IMAGE_FRONTEND }:latest

      # 4. GitOps Update
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: Akulatraxas/devops-argocd
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops

      - name: Update image tags
        run: |
          sed -i "s|webapp-backend:.*|webapp-backend:${{ github.sha }}|g" gitops/test/webapp-demo/backend.yaml
          sed -i "s|webapp-frontend:.*|webapp-frontend:${{ github.sha }}|g" gitops/test/webapp-demo/frontend.yaml

      - name: Commit & Push
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update images to ${{ github.sha }}"
          git push
